name: "Execute Scheduled Transactions / Alerts"
on:
  schedule:
    - cron: "30 8 * * *"
jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "cUrl"
        run: 'curl -XGET -H "Authorization: $API_TOKEN" "$API_URL/exec-schedule"'
